project:
  type: website
  output-dir: docs

website:
  title: ""
  sidebar:
    title: "DSAN 5000 Section 03 (Wednesdays, 3:30pm-6pm)<br><span class=\"subtitle\">Fall 2023, Georgetown</span><br><span class=\"subtitle\">Prof. Jeff <a href=\"mailto:jj1088@georgetown.edu\" target=\"_blank\"><i class=\"bi bi-envelope-at ps-1 pe-1\"></i></a><a href=\"https://github.com/jpowerj\" target=\"_blank\"><i class=\"bi bi-github ps-1\"></i></a></span>"
    contents:
      - href: "https://jfh.georgetown.domains/dsan5000/"
        text: "<i class=\"bi bi-arrow-left\" style=\"margin-right: 4px\"></i>Main Course Page"
      - "---"
      - href: index.qmd
        text: "Section 03 Home"
      - href: about.qmd
        text: "About Me"
      - href: week01.qmd
        text: "Week 1: Aug 23"
      - href: week02.qmd
        text: "Week 2: Aug 30"
      # - href: 2023-09-05.qmd
      #   text: "Week 3: Sep 6"
      - "---"
      - href: "https://forms.gle/TH1yLitU9dTfB4sg8"
        text: "Suggestion Box <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"
      - href: "https://georgetown.instructure.com/courses/173310"
        text: "Course Canvas Page <i class=\"bi bi-box-arrow-up-right ps-1\"></i>"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



